# Generated by Django 5.0.2 on 2024-03-21 10:30

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_address,
                        ],
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="consultorio/",
                        verbose_name="Imagen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultorio",
                "verbose_name_plural": "Consultorios",
            },
        ),
        migrations.CreateModel(
            name="ServiceOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Descripción",
                    ),
                ),
                ("in_time", models.TimeField(verbose_name="Hora inicial")),
                ("out_time", models.TimeField(verbose_name="Hora final")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "init_day_of_week",
                    models.CharField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                        ],
                        default=0,
                        help_text="Selecciona el dia de la semana.",
                        max_length=1,
                        verbose_name="Dia inicial del servicio",
                    ),
                ),
                (
                    "end_day_of_week",
                    models.CharField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                        ],
                        default=6,
                        help_text="Selecciona el dia de la semana.",
                        max_length=1,
                        verbose_name="Dia final del servicio",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oficoda.office",
                        verbose_name="Consultorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio de consultorio",
                "verbose_name_plural": "Servicios de consultorios",
            },
        ),
    ]
