# Generated by Django 5.0.2 on 2024-03-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oficoda", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="office",
            options={"verbose_name": "Oficoda", "verbose_name_plural": "Oficodas"},
        ),
        migrations.AlterModelOptions(
            name="serviceoffice",
            options={
                "verbose_name": "Servicio de oficoda",
                "verbose_name_plural": "Servicios de oficoda",
            },
        ),
        migrations.AlterField(
            model_name="serviceoffice",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="oficoda.office",
                verbose_name="Oficoda",
            ),
        ),
    ]
