# Generated by Django 5.0.2 on 2024-03-30 02:05

import django.core.validators
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oficoda", "0004_alter_serviceoffice_end_day_of_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceoffice",
            name="description",
            field=models.TextField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_text,
                ],
                verbose_name="Descripción",
            ),
        ),
    ]
