# Generated by Django 5.0.2 on 2024-03-21 03:03

import django.core.validators
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_address,
                        ],
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Consultorio",
                "verbose_name_plural": "Consultorios",
            },
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_address,
                        ],
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Farmacia",
                "verbose_name_plural": "Farmacias",
            },
        ),
        migrations.CreateModel(
            name="Polyclinics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_address,
                        ],
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Policlinico",
                "verbose_name_plural": "Policlinicos",
            },
        ),
    ]
