# Generated by Django 5.0.2 on 2024-03-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salud", "0002_hospital_consultingroom_image_pharmacy_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultingroom",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Imagen"
            ),
        ),
    ]
