# Generated by Django 5.0.2 on 2024-03-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salud", "0003_alter_serviceconsultingroom_end_day_of_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceconsultingroom",
            name="end_day_of_week",
            field=models.CharField(
                choices=[
                    ("Domingo", "Domingo"),
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                ],
                default="Domingo",
                help_text="Selecciona el dia de la semana.",
                max_length=9,
                verbose_name="Dia final del servicio",
            ),
        ),
        migrations.AlterField(
            model_name="serviceconsultingroom",
            name="init_day_of_week",
            field=models.CharField(
                choices=[
                    ("Domingo", "Domingo"),
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                ],
                default="Domingo",
                help_text="Selecciona el dia de la semana.",
                max_length=9,
                verbose_name="Dia inicial del servicio",
            ),
        ),
        migrations.AlterField(
            model_name="servicepolyclinics",
            name="end_day_of_week",
            field=models.CharField(
                choices=[
                    ("Domingo", "Domingo"),
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                ],
                default="Domingo",
                help_text="Selecciona el dia de la semana.",
                max_length=9,
                verbose_name="Dia final del servicio",
            ),
        ),
        migrations.AlterField(
            model_name="servicepolyclinics",
            name="init_day_of_week",
            field=models.CharField(
                choices=[
                    ("Domingo", "Domingo"),
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                ],
                default="Domingo",
                help_text="Selecciona el dia de la semana.",
                max_length=9,
                verbose_name="Dia inicial del servicio",
            ),
        ),
    ]
