# Generated by Django 5.0.2 on 2024-03-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salud", "0003_alter_consultingroom_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultingroom",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="consultorio/", verbose_name="Imagen"
            ),
        ),
    ]
