# Generated by Django 5.0.2 on 2024-03-21 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salud", "0004_alter_consultingroom_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hospital",
        ),
    ]
