# Generated by Django 5.0.2 on 2024-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salud", "0005_alter_serviceconsultingroom_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salepharmacy",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Domingo", "Domingo"),
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                ],
                help_text="Selecciona el dia de la semana.",
                max_length=10,
                verbose_name="Dia de venta",
            ),
        ),
    ]
