# Generated by Django 5.0.2 on 2024-03-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salud", "0005_delete_hospital"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalePharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                        ],
                        help_text="Selecciona el dia de la semana.",
                        max_length=1,
                        verbose_name="Dia de venta",
                    ),
                ),
                (
                    "consulting_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salud.consultingroom",
                        verbose_name="Consultorio",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salud.pharmacy",
                        verbose_name="Farmacia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta de medicamentos",
                "verbose_name_plural": "Ventas de medicamentos",
            },
        ),
    ]
