# Generated by Django 5.0.2 on 2024-03-21 10:03

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salud", "0006_salepharmacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceConsultingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Descripción",
                    ),
                ),
                ("in_date", models.DateField(verbose_name="Fecha inicial")),
                ("out_date", models.DateField(verbose_name="Fecha final")),
                ("in_time", models.TimeField(verbose_name="Hora inicial")),
                ("out_time", models.TimeField(verbose_name="Hora final")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "consulting_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salud.consultingroom",
                        verbose_name="Consultorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio de consultorio",
                "verbose_name_plural": "Servicios de consultorios",
            },
        ),
        migrations.CreateModel(
            name="ServicePolyclinics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Descripción",
                    ),
                ),
                ("in_date", models.DateField(verbose_name="Fecha inicial")),
                ("out_date", models.DateField(verbose_name="Fecha final")),
                ("in_time", models.TimeField(verbose_name="Hora inicial")),
                ("out_time", models.TimeField(verbose_name="Hora final")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "polyclinics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salud.polyclinics",
                        verbose_name="Policlinico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio de policlínico",
                "verbose_name_plural": "Servicios de policlínicos",
            },
        ),
    ]
