# Generated by Django 5.0.2 on 2024-04-06 16:10

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JovenClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Descripción')),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_address], verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_digits], verbose_name='Teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('image', models.ImageField(upload_to='joven_club/', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JCService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_text], verbose_name='Descripción')),
                ('in_time', models.TimeField(verbose_name='Hora inicial')),
                ('out_time', models.TimeField(verbose_name='Hora final')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('init_day_of_week', models.CharField(choices=[('Domingo', 'Domingo'), ('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], default='Domingo', help_text='Selecciona el dia de la semana.', max_length=9, verbose_name='Dia inicial del servicio')),
                ('end_day_of_week', models.CharField(choices=[('Domingo', 'Domingo'), ('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], default='Domingo', help_text='Selecciona el dia de la semana.', max_length=9, verbose_name='Dia final del servicio')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('jovenclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joven_club.jovenclub', verbose_name='Joven Club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
