# Generated by Django 5.0.2 on 2024-04-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joven_club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jcservice',
            name='jovenclub',
        ),
        migrations.DeleteModel(
            name='JovenClub',
        ),
    ]
