# Generated by Django 5.0.2 on 2024-03-28 00:53

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultureInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Descripción')),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_address], verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_digits], verbose_name='Teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('image', models.ImageField(upload_to='institution_culture/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Institución de cultura',
                'verbose_name_plural': 'Instituciones de cultura',
            },
        ),
        migrations.CreateModel(
            name='CultureProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField(verbose_name='Fecha inicial')),
                ('in_time', models.TimeField(verbose_name='Hora inicial')),
                ('out_date', models.DateField(verbose_name='Fecha final')),
                ('out_time', models.TimeField(verbose_name='Hora final')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Descripción')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultura.cultureinstitution', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Proyecto de cultura',
                'verbose_name_plural': 'Proyectos de cultura',
            },
        ),
    ]
