# Generated by Django 5.0.2 on 2024-03-21 09:25

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cultura", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_date", models.DateField(verbose_name="Fecha inicial")),
                ("in_time", models.TimeField(verbose_name="Hora inicial")),
                ("out_date", models.DateField(verbose_name="Fecha final")),
                ("out_time", models.TimeField(verbose_name="Hora final")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cultura.cultureinstitution",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto de cultura",
                "verbose_name_plural": "Proyectos de cultura",
            },
        ),
        migrations.DeleteModel(
            name="EducationProject",
        ),
    ]
