# Generated by Django 5.0.2 on 2024-03-21 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cultura", "0002_cultureproject_delete_educationproject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cultureinstitution",
            options={
                "verbose_name": "Institución de cultura",
                "verbose_name_plural": "Instituciones de cultura",
            },
        ),
    ]
