# Generated by Django 5.0.2 on 2024-03-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cultura", "0003_alter_cultureinstitution_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultureinstitution",
            name="image",
            field=models.ImageField(
                upload_to="institution_culture/", verbose_name="Imagen"
            ),
        ),
    ]
