# Generated by Django 5.0.2 on 2024-03-27 17:47

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Descripción')),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_address], verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_digits], verbose_name='Teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('image', models.ImageField(upload_to='institution_education/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Institución de educación',
                'verbose_name_plural': 'Instituciones de educación',
            },
        ),
        migrations.CreateModel(
            name='EducationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3), utils.validates.validates.validate_letters_numbers_and_spaces], verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacion.educationinstitution', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Proyecto de educación',
                'verbose_name_plural': 'Proyectos de educación',
            },
        ),
    ]
