# Generated by Django 5.0.2 on 2024-03-21 09:12

import django.core.validators
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
            },
        ),
    ]
