# Generated by Django 5.0.2 on 2024-03-21 09:15

import django.core.validators
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educacion", "0002_educationproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationproject",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_letters_numbers_and_spaces,
                ],
                verbose_name="Descripción",
            ),
        ),
    ]
