# Generated by Django 5.0.2 on 2024-03-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educacion", "0003_educationproject_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Institution",
            new_name="EducationInstitution",
        ),
        migrations.AlterModelOptions(
            name="educationinstitution",
            options={
                "verbose_name": "Institución de educación",
                "verbose_name_plural": "Instituciones de educación",
            },
        ),
        migrations.AddField(
            model_name="educationproject",
            name="education",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="educacion.educationinstitution",
                verbose_name="Institución",
            ),
            preserve_default=False,
        ),
    ]
