# Generated by Django 5.0.2 on 2024-03-21 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educacion", "0004_rename_institution_educationinstitution_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationproject",
            options={
                "verbose_name": "Proyecto de educación",
                "verbose_name_plural": "Proyectos de educación",
            },
        ),
    ]
