# Generated by Django 5.0.2 on 2024-03-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaterPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_date", models.DateField(verbose_name="Fecha inicial")),
                ("in_time", models.TimeField(verbose_name="Hora inicial")),
                ("out_date", models.DateField(verbose_name="Fecha final")),
                ("out_time", models.TimeField(verbose_name="Hora final")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Planificacion de acueducto",
                "verbose_name_plural": "Planificaciones de acueductos",
            },
        ),
    ]
