# Generated by Django 5.0.2 on 2024-03-21 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acueducto", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waterplanning",
            options={
                "verbose_name": "Planificación de acueducto",
                "verbose_name_plural": "Planificaciones de acueductos",
            },
        ),
    ]
