# Generated by Django 5.0.2 on 2024-03-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UNE", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affectation",
            options={
                "verbose_name": "Afectación",
                "verbose_name_plural": "Afectaciones",
            },
        ),
        migrations.AddField(
            model_name="block",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AddField(
            model_name="circuit",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ]
