# Generated by Django 5.0.2 on 2024-03-21 06:36

import django.core.validators
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UNE", "0002_alter_affectation_options_block_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    utils.validates.validates.validate_letters_numbers_and_spaces,
                ],
                verbose_name="Nombre",
            ),
        ),
    ]
