# Generated by Django 5.0.2 on 2024-03-21 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UNE", "0003_alter_block_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="circuit",
            options={"verbose_name": "Circuito", "verbose_name_plural": "Circuitos"},
        ),
    ]
