# Generated by Django 5.0.2 on 2024-03-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UNE", "0004_alter_circuit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectation",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UNE.block",
                verbose_name="Bloque",
            ),
        ),
    ]
