# Generated by Django 5.0.2 on 2024-03-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='end_day_of_week',
            field=models.CharField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], default=6, help_text='Selecciona el dia de la semana.', max_length=2, verbose_name='Dia final del servicio'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='init_day_of_week',
            field=models.CharField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], default=0, help_text='Selecciona el dia de la semana.', max_length=2, verbose_name='Dia inicial del servicio'),
        ),
    ]
