# Generated by Django 5.0.2 on 2024-03-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0006_alter_institutionservice_end_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institucion.institution', verbose_name='Institución'),
        ),
    ]
